// template-react-ssr/src/App.jsx
import reactLogo from '/react.svg';
import viteLogo from '/vite.svg';
import { useCallback, useState } from 'react';
import { increment } from './counter.js';

export function App() {
	const [counter, setCounter] = useState(0);
	const countUp = useCallback(() => {
		setCounter(counter => increment(counter));
	}, []);

	return (
		<>
			<div>
				<a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://react.dev/" target="_blank" rel="noopener noreferrer">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
				<h1>Vite + React</h1>
				<p>Wow, look at this!</p>
				<div className="card">
					<button id="counter" type="button" onClick={countUp}>
						count is {counter}
					</button>
				</div>
			</div>
		</>
	);
}

// template-vue-ssr/src/App.vue
<script setup>
import viteLogo from '/vite.svg';
import vueLogo from '/vue.svg';
import { ref } from 'vue';
import { increment } from './counter.js';

const counter = ref(0);
const countUp = () => {
	counter.value = increment(counter.value);
};
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
      <img :src="viteLogo" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">
      <img :src="vueLogo" class="logo vue" alt="Vue logo" />
    </a>
    <h1>Vite + Vue</h1>
    <p>Wow, look at this!</p>
    <div class="card">
      <button id="counter" type="button" @click="countUp">
        count is {{ counter }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.logo.vue:hover {
	filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
